GET http://localhost:3000

###

GET http://localhost:3000/flashcards/

###

GET http://localhost:3000/flashcards/6152be62a36b1a30ac41c34a

###

// Make a new flashcard

POST http://localhost:3000/flashcards
Content-Type: application/json

{
    "prompt": "Hello prompt",
    "answer": "Hello answer"
}

###

// Delete a flashcard

DELETE http://localhost:3000/flashcards/6155132fdd2dd53a70f67ddc

###

// Modify a flashcard

PATCH http://localhost:3000/flashcards/6161f9fcaae9ef757c6dfd8c
Content-Type: application/json

{
    "prompt": "Changed Prompt",
    "answer": "Changed Answer"
}

###

// Make a flashcard set

POST http://localhost:3000/flashcardsets/
Content-Type: application/json 

{
    "name": "Example flashcard set",
    "description": "Example description",
    "flashcards": [{
        "_id": "6161f26fe086797308367a83"
    },
    {
        "_id": "6161f40408bff67e28d476f4"
    }]
}

### 

GET http://localhost:3000/flashcardsets/6164ec7a7bf508689cc204b6/flashcards

###

// Get all notes

GET http://localhost:3000/notes/

###

// Create a note

POST http://localhost:3000/notes/
Content-Type: application/json

{
    "title": "test title",
    "body": "test body"
}

###

// Delete a note

DELETE http://localhost:3000/notes/

###

// Patch a note

PATCH http://localhost:3000/notes/6161f914fe6eca7514b2614c
Content-Type: application/json

{
    "title": "new title",
    "body": "changed body"
}

###

// Delete note

DELETE http://localhost:3000/notes/6161f914fe6eca7514b2614c

###

// Create a notebook

POST http://localhost:3000/notebooks
Content-Type: application/json

{
    "name": "the first notebook",
    "description": "grand new notebook",
    "notes": [{
        "_id": "615bb5d9fdad0148c6cf9baa"
    },
    {
        "_id": "615bb81c46903c4972d93096"
    },
    {
        "_id": "6161f89842965974f790b829"
    }]
}   

PATCH http://localhost:3000/notebooks/6164ee2d7bd3f819a562d6be
Content-Type: application/json

{
    "name": "the first notebook",
    "description": "grand new notebook",
    "notes": [{
        "_id": "6161f72c0647ea74a0572d5a"
    }]
}   

###        
GET http://localhost:3000/flashcardsets/
###
GET http://localhost:3000/flashcardsets/6161eb2da081f84a4c596d5c
###
GET http://localhost:3000/flashcardsets/6161eb2da081f84a4c596d5c/flashcards
###
DELETE http://localhost:3000/flashcardsets/6161eb0fa081f84a4c596d59
###
DELETE http://localhost:3000/flashcardsets/6161eb2da081f84a4c596d5c/flashcards/615529cf7ee8372c888a99d5
###
PATCH http://localhost:3000/flashcardsets/6161eb2da081f84a4c596d5c